- hosts: agent_node_group
  become: true
  remote_user: ubuntu

  tasks:
  - name: generate join command
    shell: kubeadm token create --print-join-command
    register: kubeadm_join_cmd
    delegate_to: "{{ main_node_ip }}"

  - set_fact:
      kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

  - name: join worker node to cluster
    shell: "{{ kubeadm_join }}"
    become: true
